# Site settings
title: Eat, code, feed (my babies) and repeat
description: >
  Ivan Tang has a passion for coding. He loves technology, his wife and babies.
url: 'http://hiimivantang.github.io/blog'
baseurl: '/blog/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'hiimivantang'

author:
  name: 'Ivan Tang'
  email: hiimivantang@gmail.com
  twitter_username: hiimivantang
  #facebook_username: ivantang.wx
  github_username:  hiimivantang
  linkedin_username:  hiimivantang

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
#permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
