# Site settings
title: hiimivantang
email: hiimivantang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
    Ivan Tang has a passion for coding and he loves technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: hiimivantang
github_username:  hiimivantang

# Build settings
markdown: kramdown
